### ISSUE TITLE
CloudPrediction class does not exist in new version of Function

### ISSUE THREAD

**Issue by imanirajdoost** [natmlx/videokit#107]
Since CloudPrediction class is removed since Function version 0.0.6+ it should be removed from `AudioAsset.cs` and `TextAsset.cs`

**Comment by olokobayusuf** [comment]
Hey @imanirajdoost thanks for the PR! We're working on migrating this repository so that the full Unity project is available (not just the package). Doing so means contributors like yourself have access to test scripts and other goodies. I'll keep this issue and PR open till we migrate. Thank you so much!

**Comment by olokobayusuf** [comment]
Closing this ahead of the VideoKit 0.0.18 update. It has been implemented in the current [VideoKit alpha](https://www.npmjs.com/package/ai.natml.videokit) build.
