### ISSUE TITLE
FPS drop to 3-4 in Android device on starting VideoKitCameraManager with AI capability

### ISSUE THREAD

**Issue by thesanketkale** [natmlx/videokit#70]
I see a huge FPS drop after starting the camera using VideoKitCameraManager with AI capabilities in Unity editor and Android devices. I am trying to make a QR code scanner where I need to access the camera frame texture to decode QR codes at 30 fps. It used to work quite well as per the requirements back with Natcam API, but since upgrading to VideoKit, I am seeing very low FPS once the camera feed starts.

I am using VideoKit version 0.0.15 on Unity editor version 2023.1.15f1 with Android build target platform.

My VideoKitCameraManager component looks pretty standard:
![image](https://github.com/natmlx/videokit/assets/36810188/04a6fba1-5410-407d-8102-43a0608dae0b)

The camera feed is rendered on a RawImage with standard settings:
![image](https://github.com/natmlx/videokit/assets/36810188/05f84ac1-a932-470e-bec5-fb76041cc12b)

**Comment by olokobayusuf** [comment]
Hey @thesanketkale , you're setting the preview resolution to `Highest`, which is likely going to be very very high. Try reducing it to 1920x1080 and see how the performance is like.

Enabling the `AI` capability will cause the camera image processing to run on the CPU instead of the GPU, so that AI and computer vision algorithms can access the pixel buffers to do their processing. There is a cost to this as the resolution increases.
