### ISSUE TITLE
Add basic video edition capabilities

### ISSUE THREAD

**Issue by alexandrefresnais** [natmlx/videokit#98]
Hi,

As discussed over Discord, It would be nice to have basic video edition capabilities such as rotating a video.

**Comment by olokobayusuf** [comment]
@alexandrefresnais concatenating videos is coming in 0.0.18. We can quickly add a lot of video editing capabilities, but they will all run server-side for now. We will then try to bring these back to run on-device later, given the difficulty of support for some of these operations across different platforms.

**Comment by olokobayusuf** [comment]
@alexandrefresnais we've decided not to go ahead with implementing editing functions in VideoKit because of how open-ended these editing functions can be. And composing different edits will also take a lot of processing time, as compared to having a single function that performs all the required operations.

Instead, I recommend using our [Function](https://fxn.ai) platform to write editing functions in Python (e.g. using `ffmpeg`) then using these functions from your Unity app. Feel free to follow up for more info on doing this.
